DELETE FROM QUESTION;
INSERT INTO QUESTION (ID, TITLE, LINK, LEVEL) VALUES (1, 'A', 'linkA', 'junior');
INSERT INTO QUESTION (ID, TITLE, LINK, LEVEL) VALUES (2, 'B', 'linkB', 'middle');
INSERT INTO QUESTION (ID, TITLE, LINK, LEVEL) VALUES (3, 'C', 'linkC', 'senior');