CREATE DATABASE IF NOT EXISTS db_demo;

CREATE TABLE IF NOT EXISTS Questions (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE varchar(100) NOT NULL,
    LINK varchar(100) NOT NULL,
    LEVEL varchar(10) NOT NULL,
    PRIMARY KEY(ID)
);