INSERT INTO DIFFICULTY (DIFFICULTY_NAME) VALUES
('JUNIOR'),
('MIDDLE'),
('SENIOR');

INSERT INTO QUESTION (TITLE, LINK, DIFFICULTY_ID) VALUES
('Can we override the private method in Java?', 'http://www.java67.com/2013/08/can-we-override-private-method-in-java-inner-class.html', 1),
('Difference between Hashtable and HashMap in Java?', 'http://javarevisited.blogspot.sg/2010/10/difference-between-hashmap-and.html#axzz53B6SD769', 1),
('Difference between List and Set in Java?', 'http://javarevisited.blogspot.sg/2012/04/difference-between-list-and-set-in-java.html#axzz53n9YK0Mb', 1),
('Which two methods you will override for an Object to be used as Key in HashMap?', 'http://www.java67.com/2013/06/how-get-method-of-hashmap-or-hashtable-works-internally.html', 1),
('Difference between ArrayList and LinkedList in Java?', 'http://www.java67.com/2012/12/difference-between-arraylist-vs-LinkedList-java.html', 1),
('Difference between method overloading and overriding in Java?', 'http://www.java67.com/2015/08/top-10-method-overloading-overriding-interview-questions-answers-java.html', 1),
('Difference between Polymorphism and Inheritance in Java?', 'http://www.java67.com/2014/04/difference-between-polymorphism-and-Inheritance-java-oops.html', 1),
('Can we access the private method in Java?', 'http://www.java67.com/2012/08/can-we-override-private-method-in-java.html', 1),
('Difference between interface and abstract class in Java?', 'http://www.java67.com/2017/08/difference-between-abstract-class-and-interface-in-java8.html', 1),
('Difference between throw and throws keyword in Java?', 'http://www.java67.com/2012/10/difference-between-throw-vs-throws-in.html', 1),
('Difference between this and super in Java?', 'http://www.java67.com/2013/06/difference-between-this-and-super-keyword-java.html', 1),
('How does Java achieve platform independence?', 'http://www.java67.com/2012/08/how-java-achieves-platform-independence.html', 2),
('What is ClassLoader in Java?', 'http://javarevisited.blogspot.sg/2012/12/how-classloader-works-in-java.html#axzz59AWpr6cb', 2),
('What is double checked locking in Singleton?', 'http://www.java67.com/2016/04/why-double-checked-locking-was-broken-before-java5.html', 2),
('How do you create thread-safe Singleton in Java?', 'http://javarevisited.blogspot.sg/2012/12/how-to-create-thread-safe-singleton-in-java-example.html', 2),
('When to use the volatile variable in Java?', 'http://www.java67.com/2012/08/what-is-volatile-variable-in-java-when.html', 2),
('Difference between wait and sleep in Java?', 'http://www.java67.com/2012/08/what-are-difference-between-wait-and.html', 2),
('Difference between CountDownLatch and CyclicBarrier in Java?', 'http://www.java67.com/2012/08/difference-between-countdownlatch-and-cyclicbarrier-java.html', 2),
('How does Autoboxing of Integer work in Java?', 'http://javarevisited.blogspot.sg/2012/07/auto-boxing-and-unboxing-in-java-be.html#axzz59AWpr6cb', 2),
('Difference between StringBuilder and StringBuffer in Java?', 'http://www.java67.com/2016/10/5-difference-between-stringbuffer.html', 2),
('Can we override static method in Java?', 'http://www.java67.com/2012/08/can-we-override-static-method-in-java.html', 2),
('Difference between DOM and SAX parser in Java?', 'http://www.java67.com/2012/09/dom-vs-sax-parser-in-java-xml-parsing.html', 2),
('Difference between fail-safe and fail-fast iterators in Java?', 'http://www.java67.com/2015/06/what-is-fail-safe-and-fail-fast-iterator-in-java.html', 2),
('What is the String pool in Java?', 'http://javarevisited.blogspot.sg/2016/07/difference-in-string-pool-between-java6-java7.html#axzz4pGGwsyna', 2),
('Can a Serializable class contain a non-serializable field in Java?', 'http://javarevisited.blogspot.sg/2016/09/how-to-serialize-object-in-java-serialization-example.html', 2),
('Difference between checked and unchecked Exception in Java?', 'http://javarevisited.blogspot.sg/2011/12/checked-vs-unchecked-exception-in-java.html', 2),
('Difference between Error and Exception in Java?', 'http://www.java67.com/2012/12/difference-between-error-vs-exception.html', 2),
('Difference between Race condition and Deadlock in Java?', 'http://javarevisited.blogspot.sg/2012/02/what-is-race-condition-in.html#axzz59AbkWuk9', 2),
('Stub', 'google.com', 3);
