CREATE DATABASE IF NOT EXISTS db_demo
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

USE db_demo;

CREATE TABLE IF NOT EXISTS LOCALE (
    LOCALE_ID INT NOT NULL AUTO_INCREMENT,
    LOCALE_CODE VARCHAR(10) NOT NULL,
    PRIMARY KEY(LOCALE_ID)
);

CREATE TABLE IF NOT EXISTS `LEVEL` (
    LEVEL_ID INT NOT NULL AUTO_INCREMENT,
    `TYPE` VARCHAR(10) NOT NULL,
    PRIMARY KEY(LEVEL_ID)
);

CREATE TABLE IF NOT EXISTS LEVEL_LOCALIZED (
    LEVEL_ID INT NOT NULL,
    LOCALE_ID INT NOT NULL,
    LEVEL_LOCALIZED VARCHAR(50) NOT NULL,
    FOREIGN KEY(LEVEL_ID) REFERENCES `LEVEL` (LEVEL_ID),
    FOREIGN KEY(LOCALE_ID) REFERENCES LOCALE (LOCALE_ID)
);

CREATE TABLE IF NOT EXISTS QUESTION (
    QUESTION_ID INT NOT NULL AUTO_INCREMENT,
    LINK VARCHAR(255) NOT NULL,
    LEVEL_ID INT NOT NULL,
    PRIMARY KEY(QUESTION_ID),
    FOREIGN KEY(LEVEL_ID) REFERENCES `LEVEL` (LEVEL_ID)
);

CREATE TABLE IF NOT EXISTS TITLE (
    TITLE VARCHAR(255) NOT NULL,
    LOCALE_ID INT NOT NULL,
    QUESTION_ID INT NOT NULL,
    FOREIGN KEY(LOCALE_ID) REFERENCES LOCALE (LOCALE_ID),
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION (QUESTION_ID)
);